<a href="index.php">Главная</a>
<a href="puzzle.php">Загадки</a>
<a href="guess.php">Угадайка</a>
<a href="deposit.php">Депозит</a>
<a href="guess-multiplayer.php">Угадайка-multiplayer</a>
<a href="array.php">Массив</a>
<a href="blindTyping.php">Слепая печать</a>
<a href="puzzle-homework-3.php">Загадки - 3дз</a>
<a href="password-generator.php">Генератор паролей</a>